### ISSUE TITLE
Link to terminal workshop

### ISSUE THREAD

**Issue by Yyyyaaaannnnoooo** [baselcodes/PCD2020#3]
ciao @ffd8 
thanks for the cleanup, but now the links to my tutorial got lost

**Comment by ffd8** [comment]
@Yyyyaaaannnnoooo sorrry about that! `workshops.md` Got lost/removed during my merge?? but those links have all been integrated to the main `README.md` doc – so should be alright now?

**Comment by Yyyyaaaannnnoooo** [comment]
I saw it only later...😅
